[package]
name = "pistonite-cu-proc-macros"
version = "0.1.5"
edition = "2024"
description = "Proc-macros for Cu"
repository = "https://github.com/Pistonite/cu"
license = "MIT"
authors = ["Pistonight <pistonknight@outlook.com>"]
exclude = [
    "Taskfile.yml"
]

[dependencies.pm]
package = "pistonite-pm"
version = "0.1.5"
path = "../promethium"
features = ["full"]

[lib]
proc-macro = true
