[package]
name = "pistonite-pm"
version = "0.1.2"
edition = "2024"
description = "Procedural Macro Common Utils"
repository = "https://github.com/Pistonite/cu"
license = "MIT"
authors = ["Pistonight <pistonknight@outlook.com>"]
exclude = [
    "Taskfile.yml"
]

[dependencies]
proc-macro2 = { version = "1.0.101", default-features = false }
quote = { version = "1.0.40", default-features = false }
syn = { version = "2.0.106", default-features = false }

[features]
default = [
    "base",
    "proc-macro",
]
base = [
    "syn/derive",
    "syn/parsing",
    "syn/printing",
    "syn/clone-impls",
]
proc-macro = [
    "quote/proc-macro", 
    "proc-macro2/proc-macro",
    "syn/proc-macro"
]
full = ["base", "syn/full"]
